name: Book

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ main ]
    paths:
      - "docs/**"
      - "CHANGELOG.md"
      - "CODE_OF_CONDUCT.md"
      - "LICENSE.md"
      - "README.md"
      - ".github/workflows/book.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "docs/**"
      - "CHANGELOG.md"
      - "CODE_OF_CONDUCT.md"
      - "LICENSE.md"
      - "README.md"
      - ".github/workflows/book.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  book:
    name: Book
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Install preprocessor mdbook-mermaid
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-mermaid
          version: ^0.13.0

      - name: Install preprocessor mdbook-admonish
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-admonish
          version: ^1.15.0

      - name: Install preprocessor mdbook-classy
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-classy
          git: https://github.com/wuxianucw/mdbook-classy
          branch: master

      - name: Install preprocessor mdbook-emojicodes
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-emojicodes
          version: ^0.3.0

      - name: Build Book
        working-directory: ./docs
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
