name: Rust

on:
  push:
    branches: [ main ]
    paths:
      - "modules/**/*.rs"
      - "modules/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/rust.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "modules/**/*.rs"
      - "modules/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/rust.yml"

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          #- target: x86_64-unknown-linux-musl
          #  os: ubuntu-latest
          #- target: aarch64-unknown-linux-gnu
          #  os: ubuntu-latest
          #- target: armv7-unknown-linux-gnueabihf
          #  os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: VCS Checkout
      uses: actions/checkout@v3
    - name: Install packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libgtk-3-dev libjavascriptcoregtk-4.1-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev
        version: 1.1
      if: matrix.os == 'ubuntu-latest'
    - name: Install latest nightly
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - name: Build (Release Mode)
      uses: actions-rs/cargo@v1
      with:
        command: "build"
        args: "--release --verbose"
    - name: Test (Release Mode)
      uses: actions-rs/cargo@v1
      with:
        command: "test"
        args: "--release --verbose"
